baseURL = "https://githuka.com"
title = "The Githuka's Notebook"
themesDir = "/home/wilfred/notebook/site-githuka.com/githuka.com/themes/"
theme = "m10c"
paginate = 15

[params]
  author = "Wilfred Githuka"
  description = "Never Stop Writing - Teach The World"
  avatar = "https://avic-storage.ap-south-1.linodeobjects.com/7964520.png"
  [[params.social]]
    name = "github"
    url = "https://github.com/wilfredgithuka"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/wilfredgithuka"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
